const AricaCommunes = [
    { label: "Arica", id: 0 },
    { label: "Camarones", id: 1 },
    { label: "Putre", id: 2 },
    { label: "General Lagos", id: 3 },
];

const TarapacaCommunes = [
    { label: "Iquique", id: 4 },
    { label: "Alto Hospicio", id: 5 },
    { label: "Pozo Almonte", id: 6 },
    { label: "Camiña", id: 7 },
    { label: "Colchane", id: 8 },
    { label: "Huara", id: 9 },
    { label: "Pica", id: 10 },
];

const AntofagastaCommunes = [
    { label: "Antofagasta", id: 11 },
    { label: "Mejillones", id: 12 },
    { label: "Sierra Gorda", id: 13 },
    { label: "Taltal", id: 14 },
    { label: "Calama", id: 15 },
    { label: "Ollagüe", id: 16 },
    { label: "San Pedro de Atacama", id: 17 },
    { label: "Tocopilla", id: 18},
    { label: "María Elena", id: 19 },
];

const AtacamaCommunes = [
    { label: "Copiapó", id: 20 },
    { label: "Caldera", id: 21 },
    { label: "Tierra Amarilla", id: 22 },
    { label: "Chañaral", id: 23 },
    { label: "Diego de Almagro", id: 24 },
    { label: "Vallenar", id: 25 },
    { label: "Alto del Carmen", id: 26 },
    { label: "Freirina", id: 27 },
    { label: "Huasco", id: 28 },
];

const CoquimboCommunes = [
    { label: "La Serena", id: 29 },
    { label: "Coquimbo", id: 30 },
    { label: "Andacollo", id: 31 },
    { label: "La Higuera", id: 32 },
    { label: "Paihuano", id: 33 },
    { label: "Vicuña", id: 34 },
    { label: "Illapel", id: 35 },
    { label: "Canela", id: 36 },
    { label: "Los Vilos", id: 37 },
    { label: "Salamanca", id: 38 },
    { label: "Ovalle", id: 39 },
    { label: "Combarbalá", id: 40 },
    { label: "Monte Patria", id: 41 },
    { label: "Punitaqui", id: 42 },
    { label: "Río Hurtado", id: 43 },
];

const ValparaisoCommunes = [
    { label: "Valparaíso", id: 44 },
    { label: "Casablanca", id: 45 },
    { label: "Concón", id: 46 },
    { label: "Juan Fernández", id: 47 },
    { label: "Puchuncaví", id: 48 },
    { label: "Quintero", id: 49 },
    { label: "Viña del Mar", id: 50 },
    { label: "Isla de Pascua", id: 51 },
    { label: "Los Andes", id: 52 },
    { label: "Calle Larga", id: 53 },
    { label: "Rinconada", id: 54 },
    { label: "San Esteban", id: 55 },
    { label: "La Ligua", id: 56 },
    { label: "Cabildo", id: 57 },
    { label: "Papudo", id: 58 },
    { label: "Petorca", id: 59 },
    { label: "Zapallar", id: 60 },
    { label: "Quillota", id: 61 },
    { label: "La Calera", id: 62 },
    { label: "Hijuelas", id: 63 },
    { label: "La Cruz", id: 64 },
    { label: "Nogales", id: 65 },
    { label: "San Antonio", id: 66 },
    { label: "Algarrobo", id: 67 },
    { label: "Cartagena", id: 68 },
    { label: "El Quisco", id: 69 },
    { label: "El Tabo", id: 70 },
    { label: "Santo Domingo", id: 71 },
    { label: "San Felipe", id: 72 },
    { label: "Catemu", id: 73 },
    { label: "Llay-Llay", id: 74 },
    { label: "Panquehue", id: 75 },
    { label: "Putaendo", id: 76 },
    { label: "Santa María", id: 77 },
    { label: "Quilpué", id: 78 },
    { label: "Limache", id: 79 },
    { label: "Olmué", id: 80 },
    { label: "Villa Alemana", id: 81 },

]

const OHigginsCommunes = [
    { label: "Rancagua", id: 82 },
    { label: "Codegua", id: 83 },
    { label: "Coinco", id: 84 },
    { label: "Coltauco", id: 85 },
    { label: "Doñihue", id: 86 },
    { label: "Graneros", id: 87 },
    { label: "Las Cabras", id: 88 },
    { label: "Machalí", id: 89 },
    { label: "Malloa", id: 90 },
    { label: "Mostazal", id: 91 },
    { label: "Olivar", id: 92 },
    { label: "Peumo", id: 93 },
    { label: "Pichidegua", id: 94 },
    { label: "Quinta de Tilcoco", id: 95 },
    { label: "Rengo", id: 96 },
    { label: "Requínoa", id: 97 },
    { label: "San Vicente",	 id: 98 },
    { label: "Pichilemu", id: 99 },
    { label: "La Estrella", id: 100 },
    { label: "Litueche", id: 101 },
    { label: "Marchihue", id: 102 },
    { label: "Navidad", id: 103 },
    { label: "Paredones", id: 104 },
    { label: "San Fernando", id: 105 },
    { label: "Chépica", id: 106 },
    { label: "Chimbarongo", id: 107 },
    { label: "Lolol", id: 108 },
    { label: "Nancagua", id: 109 },
    { label: "Palmilla", id: 110 },
    { label: "Peralillo", id: 111 },
    { label: "Placilla", id: 112 },
    { label: "Pumanque", id: 113 },
    { label: "Santa Cruz", id: 114 },
];

const MauleCommunes = [
    { label: "Talca", id:	115 },
    { label: "Constitución", id:	116 },
    { label: "Curepto", id:	117 },
    { label: "Empedrado", id:	118 },
    { label: "Maule", id:	119 },
    { label: "Pelarco", id:	120 },
    { label: "Pencahue", id:	121 },
    { label: "Río Claro", id:	122 },
    { label: "San Clemente", id:	123 },
    { label: "San Rafael", id:	124 },
    { label: "Cauquenes", id:	125 },
    { label: "Chanco", id:	126 },
    { label: "Pelluhue", id:	127 },
    { label: "Curicó", id:	128 },
    { label: "Hualañé", id:	129 },
    { label: "Licantén", id:	130 },
    { label: "Molina", id:	131 },
    { label: "Rauco", id:	132 },
    { label: "Sagrada Familia", id:	133 },
    { label: "Teno", id:	134 },
    { label: "Vichuquén", id:	135 },
    { label: "Linares", id:	136 },
    { label: "Colbún", id:	137 },
    { label: "Longaví", id:	138 },
    { label: "Parral", id:	139 },
    { label: "Retiro", id:	140 },
    { label: "San Javier",	 id: 141 },
    { label: "Villa Alegre", id: 142 },
    { label: "Yerbas Buenas", id: 143 },
];

const ÑubleCommunes = [
    { label: "Chillán", id: 144 },
    { label: "Bulnes", id: 145 },
    { label: "Chillán Viejo", id: 146 },
    { label: "El Carmen", id: 147 },
    { label: "Pemuco", id: 148 },
    { label: "Pinto", id: 149 },
    { label: "Quillón", id: 150 },
    { label: "San Ignacio", id: 151 },
    { label: "Yungay", id: 152 },
    { label: "Quirihue", id: 153 },
    { label: "Cobquecura", id: 154 },
    { label: "Coelemu", id: 155 },
    { label: "Ninhue", id: 156 },
    { label: "Portezuelo", id: 157 },
    { label: "Ránquil", id: 158 },
    { label: "Treguaco", id: 159 },
    { label: "San Carlos", id: 160 },
    { label: "Coihueco", id: 161 },
    { label: "Ñiquén", id: 162 },
    { label: "San Fabián", id: 163 },
    { label: "San Nicolás", id: 164 },
];

const BioBioCommunes = [
    { label: "Concepción", id: 165 },
    { label: "Coronel", id: 166 },
    { label: "Chiguayante", id: 167 },
    { label: "Florida", id: 168 },
    { label: "Hualqui", id: 169 },
    { label: "Lota", id: 170 },
    { label: "Penco", id: 171 },
    { label: "San Pedro de La Paz", id: 172 },
    { label: "Santa Juana", id: 173 },
    { label: "Talcahuano", id: 174 },
    { label: "Tomé", id: 175 },
    { label: "Hualpén", id: 176 },
    { label: "Lebu", id: 177 },
    { label: "Arauco", id: 178 },
    { label: "Cañete", id: 179 },
    { label: "Contulmo", id: 180 },
    { label: "Curanilahue", id: 181 },
    { label: "Los Álamos", id: 182 },
    { label: "Tirúa", id: 183 },
    { label: "Los Ángeles", id: 184 },
    { label: "Antuco", id: 185 },
    { label: "Cabrero", id: 186 },
    { label: "Laja", id: 187 },
    { label: "Mulchén", id: 188 },
    { label: "Nacimiento", id: 189 },
    { label: "Negrete", id: 190 },
    { label: "Quilaco", id: 191 },
    { label: "Quilleco", id: 192 },
    { label: "San Rosendo", id: 193 },
    { label: "Santa Bárbara", id: 194 },
    { label: "Tucapel", id: 195 },
    { label: "Yumbel", id: 196 },
    { label: "Alto Biobío", id: 197 },
];

const AracaniaCommunes = [
    { label: "Temuco", id: 198 },
    { label: "Carahue", id: 199 },
    { label: "Cunco", id: 200 },
    { label: "Curarrehue", id: 201 },
    { label: "Freire", id: 202 },
    { label: "Galvarino", id: 203 },
    { label: "Gorbea", id: 204 },
    { label: "Lautaro", id: 205 },
    { label: "Loncoche", id: 206 },
    { label: "Melipeuco", id: 207 },
    { label: "Nueva Imperial", id: 208 },
    { label: "Padre Las Casas", id: 209 },
    { label: "Perquenco", id: 210 },
    { label: "itrufquén", id: 211 },
    { label: "Pucón", id: 212 },
    { label: "Saavedra", id: 213 },
    { label: "Teodoro Schmidt", id: 214 },
    { label: "Toltén", id: 215 },
    { label: "Vilcún", id: 216 },
    { label: "Villarrica", id: 217 },
    { label: "Cholchol", id: 218 },
    { label: "Angol", id: 219 },
    { label: "Collipulli", id: 220 },
    { label: "Curacautín", id: 221 },
    { label: "Ercilla", id: 222 },
    { label: "Lonquimay", id: 223 },
    { label: "Los Sauces", id: 224 },
    { label: "Lumaco", id: 225 },
    { label: "Purén", id: 226 },
    { label: "Renaico", id: 227 },
    { label: "Traiguén", id: 228 },
    { label: "Victoria", id: 229 },
];

const LosRiosCommunes = [
    { label: "Valdivia", id: 230 },
    { label: "Corral", id: 231 },
    { label: "Lanco", id: 232 },
    { label: "Los Lagos", id: 233 },
    { label: "Máfil", id: 234 },
    { label: "Mariquina", id: 235 },
    { label: "Paillaco", id: 236 },
    { label: "Panguipulli", id: 237 },
    { label: "La Unión", id: 238 },
    { label: "Futrono", id: 239 },
    { label: "Lago Ranco", id: 240 },
    { label: "Río Bueno", id: 241 },
];

const LosLagosCommunes = [
    { label: "Puerto Montt", id:	242 },
    { label: "Calbuco", id:	243 },
    { label: "Cochamó", id:	244 },
    { label: "Fresia", id:	245 },
    { label: "Frutillar", id:	246 },
    { label: "Los Muermos", id:	247 },
    { label: "Llanquihue", id:	248 },
    { label: "Maullín", id:	249 },
    { label: "Puerto Varas", id:	250 },
    { label: "Castro", id:	251 },
    { label: "Ancud", id:	252 },
    { label: "Chonchi", id:	253 },
    { label: "Curaco de Vélez", id:	254 },
    { label: "Dalcahue", id:	255 },
    { label: "Puqueldón", id:	256 },
    { label: "Queilén", id:	257 },
    { label: "Quellón", id:	258 },
    { label: "Quemchi", id:	259 },
    { label: "Quinchao", id:	260 },
    { label: "Osorno", id:	261 },
    { label: "Puerto Octay", id:	262 },
    { label: "Purranque", id:	263 },
    { label: "Puyehue", id:	264 },
    { label: "Río Negro", id:	265 },
    { label: "San Juan de la Costa", id:	266 },
    { label: "San Pablo", id:	267 },
    { label: "Chaitén", id:	268 },
    { label: "Futaleufú", id:	269 },
    { label: "Hualaihué", id:	270 },
    { label: "Palena", id:	271 },
];

const AysenCommunes = [
    { label: "Coyhaique", id:272 },
    { label: "Lago Verde",	 id:273 },
    { label: "Aysén", id:274 },
    { label: "Cisnes", id:275 },
    { label: "Guaitecas", id:276 },
    { label: "Cochrane", id:277 },
    { label: "O'Higgins", id:278 },
    { label: "Tortel", id:279 },
    { label: "Chile Chico", id:280 },
    { label: "Río Ibáñez", id:281 },
];

const MagallanesCommunes = [
    { label: "Punta Arenas",	 id:282 },
    { label: "Laguna Blanca",	 id:283 },
    { label: "Río Verde",	 id:284 },
    { label: "San Gregorio",	 id:285 },
    { label: "Cabo de Hornos",	 id:286 },
    { label: "Antártica",	 id:287 },
    { label: "Porvenir",	 id:288 },
    { label: "Primavera",	 id:289 },
    { label: "Timaukel",	 id:290 },
    { label: "Natales",	 id:291 },
    { label: "Torres del Paine",	 id:292 },
];

const MetropolitanCommunes = [
    { label: "Santiago", id:	293 },
    { label: "Cerrillos", id:	294 },
    { label: "Cerro Navia", id:	295 },
    { label: "Conchalí", id:	296 },
    { label: "El Bosque", id:	297 },
    { label: "Estación Central", id:	298 },
    { label: "Huechuraba", id:	299 },
    { label: "Independencia", id:	300 },
    { label: "La Cisterna", id:	301 },
    { label: "La Florida", id:	302 },
    { label: "La Granja", id:	303 },
    { label: "La Pintana", id:	304 },
    { label: "La Reina", id:	305 },
    { label: "Las Condes", id:	306 },
    { label: "Lo Barnechea", id:	307 },
    { label: "Lo Espejo", id:	308 },
    { label: "Lo Prado", id:	309 },
    { label: "Macul", id:	310 },
    { label: "Maipú", id:	311 },
    { label: "Ñuñoa", id:	312 },
    { label: "Pedro Aguirre Cerda", id:	313 },
    { label: "Peñalolén", id:	314 },
    { label: "Providencia", id:	315 },
    { label: "Pudahuel", id:	316 },
    { label: "Quilicura", id:	317 },
    { label: "Quinta Normal", id:	318 },
    { label: "Recoleta", id:	319 },
    { label: "Renca", id:	320 },
    { label: "San Joaquín", id:	321 },
    { label: "San Miguel", id:	322 },
    { label: "San Ramón", id:	323 },
    { label: "Vitacura", id:	324 },
    { label: "Puente Alto", id:	325 },
    { label: "Pirque", id:	326 },
    { label: "San José de Maipo", id:	327 },
    { label: "Colina", id:	328 },
    { label: "Lampa", id:	329 },
    { label: "Til Til",	 id:	330 },
    { label: "San Bernardo", id:	331 },
    { label: "Buin", id:	332 },
    { label: "Calera de Tango", id:	333 },
    { label: "Paine", id:	334 },
    { label: "Melipilla", id:	335 },
    { label: "Alhué", id:	336 },
    { label: "Curacaví", id:	337 },
    { label: "María Pinto", id:	338 },
    { label: "San Pedro", id:	339 },
    { label: "Talagante", id:	340 },
    { label: "El Monte", id:	341 },
    { label: "Isla de Maipo", id:	342 },
    { label: "Padre Hurtado", id:	343 },
    { label: "Peñaflor", id:	344 },
];

export const allRegions = () => {
    let regions = []
    AricaCommunes.forEach((commune, index) => regions.push( commune ));
    TarapacaCommunes.forEach((commune, index) => regions.push( commune ));
    AntofagastaCommunes.forEach((commune, index) => regions.push( commune ));
    AtacamaCommunes.forEach((commune, index) => regions.push( commune ));
    CoquimboCommunes.forEach((commune, index) => regions.push( commune ));
    ValparaisoCommunes.forEach((commune, index) => regions.push( commune ));
    OHigginsCommunes.forEach((commune, index) => regions.push( commune ));
    MauleCommunes.forEach((commune, index) => regions.push( commune ));
    ÑubleCommunes.forEach((commune, index) => regions.push( commune ));
    BioBioCommunes.forEach((commune, index) => regions.push( commune ));
    AracaniaCommunes.forEach((commune, index) => regions.push( commune ));
    LosRiosCommunes.forEach((commune, index) => regions.push( commune ));
    LosLagosCommunes.forEach((commune, index) => regions.push( commune ));
    AysenCommunes.forEach((commune, index) => regions.push( commune ));
    MagallanesCommunes.forEach((commune, index) => regions.push( commune ));
    MetropolitanCommunes.forEach((commune, index) => regions.push( commune ));
    return regions
}